apiVersion: v1
kind: Pod
metadata: 
  name: dotnet-core-client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: peelmicro/dotnet-core-multi-client:latest
      ports: 
        - containerPort: 3000
